version: 2
updates:
  # Maintain dependencies for the Dockerfile
  - package-ecosystem: "docker"
    directory: "/" 
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "area: docker"

  # Maintain dependencies for Python packages
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "area: python"

  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type: dependencies"
      - "area: actions"
