title: Wonderful Wino Documentation
description: Documentation for the Wonderful Wino add-on

# GitHub Pages whitelisted theme with dark red accent
theme: jekyll-theme-merlot

# Optional: include custom CSS
defaults:
  -
    scope:
      path: ""
    values:
      custom_css: assets/css/custom.css
