title: Wonderful Wino Documentation
description: Documentation for the Wonderful Wino Home Assistant add-on

# Minimal, wide theme
theme: jekyll-theme-slate

# Optional: include custom CSS
defaults:
  -
    scope:
      path: ""
    values:
      custom_css: assets/css/custom.css
